### ISSUE TITLE
package-lock.json not respecting 'skip'

### ISSUE THREAD

**Issue by Keidrych** [dependencyci/support#100]
Tried the following:

```
packages:
  NPM:
    tests:
      unlicensed: skip
    nomnom:
      tests:
        unmaintained: skip
```
and 
```
files:
  'package-lock.json':
    tests:
      unlicensed: skip
    nomnom:
      tests:
        unmaintained: skip
```

In both cases, package-lock tests run and don't respect the skip settings causing failing builds. Anything I'm missing in the config?
