### ISSUE TITLE
Cannot skip unmaintained test for a RubyGem dependency

### ISSUE THREAD

**Issue by JuanitoFatas** [dependencyci/support#26]
I would like to skip the `unmaintained` check for [this RubyGem github-markdown][github-markdown] dependency, but it [still checks](https://dependencyci.com/builds/2997), [this is the content of my `dependencyci.yml`](https://github.com/JuanitoFatas/JuanitoFatas/blob/6d5861d8b557399f66244f9d871f1f511a1f323b/dependencyci.yml):

```yaml
# dependencyci.yml
platform:
  Rubygems:
    github-markdown:
      tests:
        unmaintained: skip
```

[github-markdown]: https://rubygems.org/gems/github-markdown

Please advise, thanks!
