### ISSUE TITLE
Deprecation skipping not working

### ISSUE THREAD

**Issue by LongLiveCHIEF** [dependencyci/support#40]
I'm using [webpack-validator](https://npmjs.org/packages/webpack-validator), which is shown as *deprecated* on libraries.io.  It turns out, the npm package now points to the correct *non-deprecated* install, and libraries.io just hasn't figured that out yet.

In the meantime, I tried to fix the problem, by adding a `dependencyci.yml` file as follows:

```yml
platform:
  npm:
    webpack-validator:
      tests:
        deprecated: skip
```

However, the `deprecated` test is still running for this dependency, and [causing build failure](https://dependencyci.com/github/HackerHappyHour/lgit/builds/9).
